using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using MintyCore.Utils;

namespace MintyCore.ECS;

/// <summary>
///   Interface to manage archetypes and their components
/// </summary>
public interface IArchetypeManager
{
    /// <summary>
    /// 
    /// </summary>
    /// <param name="archetypeId"></param>
    /// <param name="setup"></param>
    /// <returns></returns>
    bool TryGetEntitySetup(Identification archetypeId, [MaybeNullWhen(false)] out IEntitySetup setup);

    /// <summary>
    ///   Create a new ArchetypeStorage for a given archetype id
    /// </summary>
    /// <param name="archetypeId"></param>
    /// <returns></returns>
    IArchetypeStorage CreateArchetypeStorage(Identification archetypeId);

    /// <summary>
    ///  Add a new archetype to the manager
    /// </summary>
    /// <param name="archetypeId"> ID of the archetype </param>
    /// <param name="archetype"> The archetype to add </param>
    /// <param name="entitySetup"> Optional entity setup for the archetype </param>
    void AddArchetype(Identification archetypeId, ArchetypeContainer archetype,
        IEntitySetup? entitySetup);

    /// <summary>
    ///     Get the ArchetypeContainer for a given archetype id
    /// </summary>
    /// <param name="archetypeId">id of the archetype</param>
    /// <returns>Container with the component ids of an archetype</returns>
    ArchetypeContainer GetArchetype(Identification archetypeId);

    /// <summary>
    ///     Get all registered archetype ids with their specific ArchetypeContainers
    /// </summary>
    /// <returns>ReadOnly Dictionary with archetype ids and ArchetypeContainers</returns>
    IReadOnlyDictionary<Identification, ArchetypeContainer> GetArchetypes();

    /// <summary>
    ///     Check if the archetype has a specific component
    /// </summary>
    /// <param name="archetypeId">The archetype to check</param>
    /// <param name="componentId">The component to check</param>
    /// <returns>Whether or not the component is present</returns>
    bool HasComponent(Identification archetypeId, Identification componentId);

    /// <summary>
    ///   Clear all internal data
    /// </summary>
    void Clear();
    
    /// <summary>
    /// Remove a archetype from the manager
    /// </summary>
    /// <param name="objectId"> ID of the archetype to remove </param>
    void RemoveArchetype(Identification objectId);
    
    /// <summary>
    /// Remove all assemblies source generated by the manager
    /// </summary>
    void RemoveGeneratedAssemblies();
}